# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('codeforces_id', models.CharField(max_length=30)),
                ('bestcoder_id', models.CharField(max_length=30)),
                ('hdu_id', models.CharField(max_length=30)),
                ('poj_id', models.CharField(max_length=30)),
            ],
        ),
    ]
