# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bestcoder_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='codeforces_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hdu_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='poj_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='vj_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vj_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bestcoder_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforces_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hdu_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='poj_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
