# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankList', '0003_auto_20161225_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tot',
            field=models.FloatField(null=True),
        ),
    ]
